title: Passcode:Settings
description: Use this configuration to define passcode policy settings
payload:
  declarationtype: com.apple.configuration.passcode.settings
  supportedOS:
    iOS:
      introduced: '15.0'
      sharedipad:
        mode: forbidden
    macOS:
      introduced: '13.0'
      userenrollment:
        mode: forbidden
    tvOS:
      introduced: n/a
payloadkeys:
- key: RequirePasscode
  title: Require Passcode on Device
  type: <boolean>
  presence: optional
  default: false
  content: If 'true', requires the user to set a passcode without any requirements
    about the length or quality of the passcode. The presence of any other keys implicitly
    requires a passcode, and overrides this key's value.
- key: RequireComplexPasscode
  title: Require Complex Passcode
  type: <boolean>
  presence: optional
  default: false
  content: If 'true', requires a complex passcode. A complex passcode is one that
    doesn't contain repeated characters or increasing/decreasing characters (such
    as 123 or CBA), and must contain at least one nonnumeric/nonalphabetic character.
- key: MinimumLength
  title: Minimum Passcode Length
  type: <integer>
  presence: optional
  range:
    min: 0
    max: 16
  default: 0
  content: The minimum number of characters a passcode can contain.
- key: MaximumFailedAttempts
  title: Maximum Number of Failed Attempts
  type: <integer>
  presence: optional
  range:
    min: 2
    max: 11
  default: 11
  content: |-
    The number of failed passcode attempts that the system allows the user before iOS erases the device or macOS locks the device. If you don't change this setting, after six failed attempts, the device imposes a time delay before the user can enter a passcode again. The time delay increases with each failed attempt.
    After the final failed attempt, the system securely erases all data and settings from the iOS device. A macOS device locks after the final attempt. The passcode time delay begins after the sixth attempt, so if this value is six or lower, the system has no time delay and triggers the erase or lock as soon as the user exceeds the limit.
- key: MaximumGracePeriodInMinutes
  title: Maximum Grace Period
  type: <integer>
  presence: optional
  content: |-
    The maximum period that a user can select, during which the user can unlock the device without a passcode. A value of '0' means no grace period, and the device requires a passcode immediately. In the absence of this key, the user can select any period.
    macOS translates this to screensaver settings.
- key: MaximumInactivityInMinutes
  title: Automatic Device Lock
  type: <integer>
  presence: optional
  range:
    min: 0
    max: 15
  content: |-
    The maximum period that a user can select, during which the device can be idle before the system automatically locks it. When the device reaches this limit, the device locks and the user must enter the passcode to unlock it. In the absence of this key, the user can select any period.
    macOS translates this to screensaver settings.
- key: PasscodeReuseLimit
  title: Passcode Reuse Limit
  type: <integer>
  presence: optional
  range:
    min: 1
    max: 50
  content: The number of historical passcode entries the system checks when vaildating
    a new passcode. The device refuses a new passcode if it matches a previously used
    passcode within the specified passcode history range. In the absence of this key,
    the system performs no historical check.
